%define    C_BLACK               0 
%define    C_BLUE                1 
%define    C_GREEN               2 
%define    C_CYAN                3 
%define    C_RED                 4 
%define    C_MAGENTA             5 
%define    C_BROWN               6 
%define    C_LIGHT_GRAY          7 
%define    C_DARK_GRAY           8 
%define    C_LIGHT_BLUE          9 
%define    C_LIGHT_GREEN         A 
%define    C_LIGHT_CYAN          B 
%define    C_LIGHT_RED           C 
%define    C_LIGHT_MAGENTA       D 
%define    C_YELLOW              E 
%define    C_WHITE               F