; constants only

; START_ENSURE_SAME_gdt_h

GDT_STD_SELECTOR_NULL       EQU     0
GDT_STD_SELECTOR_KERNEL_CS  EQU     1
GDT_STD_SELECTOR_KERNEL_DS  EQU     2
GDT_STD_SELECTOR_ABS16_CS   EQU     3
GDT_STD_SELECTOR_ABS16_DS   EQU     4
GDT_STD_SELECTOR_ABS32_DS   EQU     6
GDT_STD_SIZE                EQU     5 ; FIX

GDT_STD_SIZEOF_ENTRY        EQU     8
; END_ENSURE_SAME_gdt_h

GDT_NULL_CS     EQU   (GDT_STD_SELECTOR_NULL*GDT_STD_SIZEOF_ENTRY)
GDT_KERNEL_CS   EQU   (GDT_STD_SELECTOR_KERNEL_CS*GDT_STD_SIZEOF_ENTRY)
GDT_KERNEL_DS   EQU   (GDT_STD_SELECTOR_KERNEL_DS*GDT_STD_SIZEOF_ENTRY)
GDT_ABS16_CS    EQU   (GDT_STD_SELECTOR_ABS16_CS*GDT_STD_SIZEOF_ENTRY)
GDT_ABS16_DS    EQU   (GDT_STD_SELECTOR_ABS16_DS*GDT_STD_SIZEOF_ENTRY)
GDT_ABS32_DS    EQU   (GDT_STD_SELECTOR_ABS32_DS*GDT_STD_SIZEOF_ENTRY)
