name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Prerequisite
      run: sudo bash before_install.sh

    - name: make
      run: make

    - name: make test
      run: make test

    - name: Get current time
      uses: 1466587594/get-current-time@v2
      id: current-time
      with:
        format: YYYY-MM-DD HH:mm
        utcOffset: "+00:00"

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ steps.current-time.outputs.formattedTime }} UTC
        draft: false
        prerelease: false
        commitish: ${{ github.sha }}

    - name: Upload Raw Image
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/FuzzyOS.raw
        asset_name: FuzzyOS.raw
        asset_content_type: application/octet-stream

    - name: Upload Virtual Box Image
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/FuzzyOS.vdi
        asset_name: FuzzyOS.vdi
        asset_content_type: application/x-virtualbox-vdi

    - name: Upload VMWare Image
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/FuzzyOS.vmdk
        asset_name: FuzzyOS.vmdk
        asset_content_type: application/x-vmdk
